server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/${DB_NAME:neuronexus_db}
    username: ${DB_USER:neuronexus}
    password: ${DB_PASSWORD:devpass}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
